ScilifelabDataCentre/serve

.github/PULL_REQUEST_TEMPLATE/chart.md, .github/pull_request_template.md
An early version of a chart-specific PR template. Currently there is a checklist of some security-related issues that should be fixed in any new charts. It is intended to grow as I see what things are missing/often done wrong in the current charts.
The template will not replace the default one. Instead it will be available if you add the parameter `?template=chart.md` once you make it to the "Open a pull request" window. If there is already a parameter (`?key=val`) at the end of the url, you add `&template=chart.md` instead. The url will then be similar to `https://github.com/ScilifelabDataCentre/stackn/compare/main...ScilifelabDataCentre:stackn:dc-develop?template=chart.md`.
_If you're unsure about any of the items below, don't …
=> Add a PR template specific for Helm charts

portal/views.py
Bug description: 
When logged out, public apps and model and news were not visible on the base url (e.g., studio.127.0.0.1.nip.io:8080/), but were visible on `/home`, (e.g., studio.127.0.0.1.nip.io:8080/home).
Bug fix:
Very simple. Instead of returning a rendering of template from `HomeViewDynamic`, i instead return the rendered template from `HomeView`. 
=> SS-701 - Public apps should be visible when logged out 

.pre-commit-config.yaml, fixtures/projects_templates.json
Bug : minio is setting persistent volume as none by default
Fix: Make sure that the volume is created before minio, so it can mount to it. 
=> SS-721 -  minio is setting persistent volume as none by default

studio/settings.py
This PR adds CORS rules to allow all clients to make requests to the OpenAPI endpoints. I have tested with a js client that a few OpenAPI endpoints are allowed while denying URL:s outside the openapi relative paths.
Jira [link](https://scilifelab.atlassian.net/browse/SS-729)
=> SS-729 Resolved CORS for OpenApi

api/views.py, apps/helpers.py, apps/tests/test_update_status_handler.py
Fixed updating of the app status when the status code text is longer than 15 chars. 
Jira [link](https://scilifelab.atlassian.net/browse/SS-907)
=> SS-907 Fixed update of long app status texts

charts/apps/minio/chart/templates/deployment.yaml
Minio didn't run its `postStartHook` properly. It failed on the create bucket step if the bucket already exists. 
I've added `|| true` catch this. 
The logic is like this: Either it creates it and returns success, or it has already been created, so it's fine anyways. 
Tried this on 5 running minio instances and it worked. 
=> Fixed bug where minio crashed when bucket existed

charts/apps/tissuumaps/chart/values.yaml, fixtures/apps_fixtures.json, studio/settings.py, templates/apps/create.html
This PR completes the new app type TissUUmaps by improving the user information texts in the UI. It also sets the max number of TissUUmaps app instances per project to 1. There is an associated change to the settings.py configmap in the serve-charts repo.
=> SS-841 Polishing app type tissuumaps

charts/apps/custom-app/chart/templates/deployment.yaml, charts/apps/dash/chart/templates/deployment.yaml, charts/apps/python-serve/chart/templates/deployment.yaml, charts/apps/shiny/chart/templates/deployment.yaml, charts/apps/shinyproxy/chart/templates/configmap.yaml, charts/apps/tissuumaps/chart/templates/deployment.yaml, templates/apps/create.html, templates/apps/update.html
In this PR I set the ImagePullPolicy to IfNotPresent so that the cluster does not retrieve new versions of the images that users supply unless the new version has a unique tag. It solves the issue [SS-927](https://scilifelab.atlassian.net/browse/SS-927).
=> Add requirement for unique docker image tags for each version of depoyed apps

charts/apps/tissuumaps/chart/templates/deployment.yaml, charts/apps/tissuumaps/chart/templates/tissuumaps-configmap.yaml
This PR makes 2 adjustments to the TissUUmaps app type. The image pull policy is set to Always and two additional settings are added to the configuration file to support version 3.2.0.5. 
=> SS 841 Adjust the TissUUmaps pull policy and configuration

apps/serialize.py
[SS-950](https://scilifelab.atlassian.net/browse/SS-950?atlOrigin=eyJpIjoiMGNmZjMyMmYyMDJhNDE3YmFiNzg1YjA2ZTgzMzIyNDAiLCJwIjoiaiJ9)
It turns out that the solution for this was simple and quite elegant, but it took some time to figure out. See the flow chart.
Issue: Users could not create apps with comma or any other chars
Reason: We save the helm charts using `app_name`, and a helm chart can only use numbers, alphabet and `-`. 
Solution: Slugify `app_name` when it is set in the parameters dict.
=> SS 950 apps fail if names contains comma

charts/apps/tissuumaps/chart/templates/ingress.yaml
Fixing missed auth url header for link only apps in tissuumaps.
=> update chart with ingress link only logic

Dockerfile, api/APIpermissions.py, api/views.py, portal/views.py, studio/settings.py
This PR adds the ability to add expiration to API authentication tokens. To use add the permission class IsTokenAuthenticated to the function decorator. There is one configuration setting to set the expiration duration called AUTH_TOKEN_EXPIRATION
Jira [link](https://scilifelab.atlassian.net/browse/SS-871)
=> SS 871 Authentication token expiry

templates/404.html
This draft PR add a template for django pages that are not found. For the pages, that won't be found on the k8s side, we need to a page on rancher side. @hamzaimran08 said, that he would provide more info on this the SS-887 task.
- [ x ] This pull request is against **develop** branch (not applicable for hotfixes)
- [ x ] I have included a link to the issue on GitHub or JIRA (if any)
- [ x ] I have added a reviewer for this pull request
- [ x ] I have added myself as an author for this pull request
Anything else you think we should …
=> SS-887-custom-404-page

apps/generate_form.py
https://scilifelab.slack.com/archives/C02L5Q7HWR1/p1713276097488319?thread_ts=1712926435.438649&cid=C02L5Q7HWR1
The problem was that when user had their app created before introduction of `link only` persmission option, they would get broken permissions in settings. This pr addresses this issue
- [ x ] This pull request is against **develop** branch (not applicable for hotfixes)
- [ x ] I have added a reviewer for this pull request
- [ x ] I have added myself as an author for this pull request
Anything else you think we should know …
=> fix-missing-link-only-option-in-old-apps

apps/views.py, templates/apps/create_base.html
Update app creation template so that title would change based on users intent to update app settings or to create an app
=> SS-1043 Update app creation template header

common/forms.py, templates/registration/password_reset_confirm.html, templates/registration/signup.html
When we were upgrading signup form, we've forgotten to add a help text for the password field. This PR fixes that. 
=> SS-1101 Add password help text to the signup and password reset forms

templates/apps/partials/srv_prepend_append_input_group.html
The fix is easy, just needed to add errors to the custom template that we use for the input group
- [x ] I have added a reviewer for this pull request
- [x ] I have added myself as an author for this pull request
=> SS-1133 Added errors display for shiny site dir

apps/helpers.py
Small fix that enables redeployment of shiny apps in case `shiny_site_dir` is changed
=> Added `shiny_site_dir` as a field that triggers redeployment

apps/forms/dash.py, apps/forms/gradio.py, apps/forms/shiny.py, apps/forms/streamlit.py, apps/tasks.py, cypress/e2e/ui-tests/test-public-webpages.cy.js, cypress/e2e/ui-tests/test-signup.cy.js, fixtures/apps_fixtures.json, templates/apps/logs.html
This PR contains fixes for bugs that we discovered before 2.2.0 release.
- A few e2e tests were broken because of changes in previous PRs.
- Periodic task to remove apps of type develop and file managers that are old incorrectly tried to delete already deleted apps again
- The copy data logs were not shown for gradio and streamlit app types
- Now temporarily disabled private and project permission options for gradio apps
- Update shinyproxy chart version
- Better placeholder for docker image field in app creation/edit form
=> Bugfixes before release 2.2.0

apps/views.py, projects/views.py, templates/projects/partials/app_templates.html
This PR relates to issue SS-1126. Previously, after project deletion if the user would try to open the deleted project page (e.g. it was bookmarked) they would get stuck in an infinite refresh loop. In case of superusers, they are informed that they are trying to access a project that has been removed.
=> SS-1126 Remove access to project after deletion

cypress/e2e/ui-tests/test-deploy-app.cy.js
Source: https://scilifelab.atlassian.net/browse/SS-1190
The task is to add appropriate tests for these app types where needed in e2e tests.
=> SS-1190 e2e tests for gradio and streamlit app deployment

apps/forms/base.py, apps/tasks.py, apps/tests/test_delete_app_view.py, apps/views.py, projects/tasks.py, studio/settings.py, templates/apps/create_base.html, templates/apps/create_view.html
This PR fixes the issue SS-1229. We didn't save the _deleted_on_ date when an app was deleted by the users. In addition, I added timezone info to the saved value. I also added a unit test to check that this field was populated on deletion.
This PR also fixes the issue SS-1238. Persistent volumes that were deleted were shown as options when launching a file manager or notebooks.
Finally, unrelated change - fixed the links to documentation from the app creation/edit form because we missed that in past PRs.
=> SS-1229 Fix of the bug not saving deleted on date

portal/views.py
Hotfix to display only the first 6 apps on the homepage.
=> restrict N of apps on the homepage to only 6

apps/tasks.py
When deleting an app that doesn't have a subdomain display a pre-defined error
Source: https://scilifelab.atlassian.net/browse/SS-1247
=> SS-1247 when deleting an app that doesn't have a subdomain display a pre defined error

.github/workflows/e2e-tests.yaml, projects/views.py, studio/views.py
To set the status of the pull request, use the built-in github feature to set the PR as Draft or Ready for review.
Jira ticket: [https://scilifelab.atlassian.net/browse/SS-964](https://scilifelab.atlassian.net/browse/SS-964)
A project owner may give access to their project. Notify the user via email when access is granted.
=> SS-964 Send email confirmation on project access

apps/forms/base.py, apps/forms/filemanager.py, cypress/e2e/ui-tests/test-brute-force-login-attempts.cy.js, cypress/e2e/ui-tests/test-deploy-app.cy.js, cypress/e2e/ui-tests/test-login-account-handling.cy.js, cypress/e2e/ui-tests/test-project-as-contributor.cy.js, cypress/e2e/ui-tests/test-public-webpages.cy.js, cypress/e2e/ui-tests/test-superuser-functionality.cy.js, cypress/e2e/ui-tests/test-views-as-reader.cy.js, static/css/serve-colors.css, static/css/serve-elements.css, static/css/serve-utilities.css, templates/common/app_card.html, templates/common/app_card_docker_info.html, templates/common/navbar.html, templates/portal/apps.html, templates/projects/partials/app_instances_table.html, templates/projects/partials/app_templates.html, templates/projects/project_create.html, templates/registration/password_change_form.html, templates/registration/password_reset_form.html, templates/registration/signup.html, templates/user/profile.html, templates/user/profile_edit_form.html
This change relates to issue [SS-1204](https://scilifelab.atlassian.net/browse/SS-1204). There are many front-end changes in this one but mainly the following parts have been changed
- App Edit/Create forms
- Navbar
- App Cards on Public Apps page
- Project Apps page
- User profile and edit profile pages
- Sign up and password change forms
=> SS-1204 harmonize frontend

api/views.py, apps/admin.py, apps/constants.py, apps/helpers.py, apps/tasks.py, apps/tests/test_app_helper_utils.py, apps/tests/test_update_status_handler.py, apps/views.py, projects/tasks.py, templates/projects/categories/develop.html
This PR is a hotfix against the production (main) branch. It fixes a bug in version 3.0.0 with the function that should delete old file manager and Jupyter Lab notebook apps. It sets the latest user action code to SystemDeleting for any apps that are deleted by the system itself (vs end user) thereby correctly handling these in the UI and k8s deletion task. It does so by introducing a required argument initiated_by (AppActionOrigin) to the delete_resource task to indicate the initiating source of the action.
For more information and recommended tests to verify, see:
Jira [link](https://scilifelab.atlassian.net/browse/SS-1348)
=> SS 1348 Hotfix to fix function to cleanup old file manager and notebook apps

api/views.py, apps/constants.py, apps/helpers.py, apps/tests/test_update_status_handler.py, docker-compose.yaml, scripts/run_web.sh
This PR uses the latest event-listener service which upgrades the Kubernetes Python API to version 32. There are some other minor changes, such as a delay introduced in the event-listener when handling Deleted events. Also requests to update non-existent app instances is treated as less severe as this can happen for non-catastrophic reasons.
It also adds a close-sessions flag to the reset_db handling for local and development environments when re-creating the database.
Jira [link](https://scilifelab.atlassian.net/browse/SS-1374)
=> SS 1374 Upgrade the event listener k8s API

cypress/e2e/ui-tests/test-login-account-handling.cy.js
An E2E test is failing on the develop branch (see image attached).
=> Bug: Password URL error in E2E tests

cypress/e2e/integration-tests/test-deploy-app.cy.js, cypress/e2e/ui-tests/test-user-manage-apps.cy.js
When creating or updating an app with an invalid container image, the form is submitted without validation. We need to modify the tests so that the app update does not go through, inline with the more recent expected behaviour.
=> Bug: Explicit error on bad container image

cypress/e2e/ui-tests/test-project-as-contributor.cy.js, cypress/e2e/ui-tests/test-superuser-functionality.cy.js
Fix the failing E2E test on the develop branch.
=> Bug: fix latest E2E test failure on develop

apps/types_/subdomain.py, apps/views.py, templates/apps/secrets_view.html
Ready for review
1. MLFlow: When user opens secrets page and agrees to auto fill credentials, mlflow credentials overridden
Source: https://scilifelab.atlassian.net/browse/SS-1398
2. MLFlow: When user sets subdomain with `mlflow` in it, secrets are not generated according to the `secrets page` pattern
Source: https://scilifelab.atlassian.net/browse/SS-1397
The root cause of the mlflow subdomain bug is that, the chart avoids redundant naming when the release name already contains mlflow, but appends -mlflow otherwise. This conditional logic is why only mlflow-containing subdomains fail. The logic is implemented [here: ](https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_names.tpl#L21-L37). From there,
`If release name contains chart name it will be used as a full name.` …
=> SS-1398 mlflow subdomain bug fix

apps/forms/mlflow.py
Notice: this PR is pointed directly to the staging branch
This pull request includes changes to the `apps/forms/mlflow.py` file, enhancing the user interface and providing important information to users about the experimental nature of the MLFlow app feature.
User Interface Improvements:
* [`apps/forms/mlflow.py`](diffhunk://#diff-7598b8833346d29abf14b6a0385e309e95eaadf1c0f9582dabf2f70ef4b1279dL1-R1): Added an `HTML` import from `crispy_forms.layout` to support the inclusion of HTML content in the form.
* [`apps/forms/mlflow.py`](diffhunk://#diff-7598b8833346d29abf14b6a0385e309e95eaadf1c0f9582dabf2f70ef4b1279dR15-L16): Introduced an HTML block in the `_setup_form_helper` method to display an experimental feature notice and additional guidance for users.
To indicate the type of change …
=> Remove subdomain field from the MLFlow form

api/openapi/content_stats_api.py, api/openapi/urls.py, api/tests/test_openapi_content_stats.py
This PR adds an Open API endpoint with current and past content aggregated statistics such as the number of projects and apps.
The API resource is named content-stats and can be reached at endpoint /openapi/v1/content-stats
Jira [link](https://scilifelab.atlassian.net/browse/SS-1442)
=> SS -1442 Add API for Serve content stats

studio/settings.py
This PR configures AXES brute force protection to work with client IP:s considering reverse proxy servers and load balancer environments by adding 2 new settings to the Django settings:
AXES_IPWARE_PROXY_COUNT
AXES_IPWARE_META_PRECEDENCE_ORDER
Jira [link](https://scilifelab.atlassian.net/browse/SS-1149)
=> SS-1149 Configure AXES to use client IP

static/css/serve-utilities.css, templates/common/app_card.html, templates/portal/apps.html
Small UI fixes for release 3.2.0
=> add UI fixes for pagination, app cards and nav

api/openapi/content_stats_api.py, api/tests/test_openapi_content_stats.py
This PR makes two small adjustments to the content stats API. It adds a new metric n_apps_public for the number of public apps. It adds a new count to the image registry dict "noimage" for any apps that have no labeled image. 
=> Adjust content stats API apps

Dockerfile, apps/models/app_types/mlflow.py
This change satisfies updates from https://github.com/bitnami/containers/issues/83267
=> Fix references to bitnami images in Dockerfile and mlflow.py

api/services/loki.py, apps/helpers.py, apps/tasks.py, fixtures/intervals_fixtures.json, fixtures/periodic_tasks_fixtures.json, projects/views.py, studio/settings.py, templates/projects/partials/app_instances_table.html
https://scilifelab.atlassian.net/browse/SS-1523
Create a Celery task that runs a Loki query to collect unique IP visits to every app on Serve in the last 30 days. The value is saved in Redis using Django cache and then displayed on the user project view.
=> ss-1523 Integrate app IP count into Serve UI

README.md, apps/types_/kubernetes_deployment_manifest.py, cypress/e2e/integration-tests/test-deploy-app.cy.js
This PR fixes two failing integration tests. One test lacked proper visibility verifications around a model and nested button. The other test failed caused by missing required app description. Also added many should('be.visible') clauses to make tests more robust and also cleaned up some comments. I also converted one obsolete test to test that redeploy of shiny apps works in regards to the app status when changing the docker image. This test may fail until the app status code fixes this.
For some background, see Jira [link](https://scilifelab.atlassian.net/browse/SS-1254)
=> Fix integration tests

templates/portal/roadmap.html
This PR updates the Serve roadmap given the current status and planned and completed major work.
Jira [link](https://scilifelab.atlassian.net/browse/SS-1518)
=> SS 1518 Update the Serve roadmap
