components/studio/templates/teaching.html
Page about using Serve for teaching.
=> first draft of page about teaching

components/studio/templates/teaching.html
- [ X] Draft
I have polished the language on this page a bit. The aim was only to make it read a bit more smoothly. We might need to edit a few parts, as we need to discuss some details in our next meeting
- [X ] Documentation update
=> Polish teaching text

components/studio/templates/base.html, components/studio/templates/user_guide.html
Added instructions related to gaining and account and logging in.
NA
=> Add log in instructions

.github/workflows/build-studio.yaml, components/studio/projects/templates/settings.html, components/studio/requirements.txt, components/studio/templates/home.html
Describe your changes here to communicate to the maintainers why we should accept this pull request. 
=> Grant access project flow

components/studio/projects/templates/settings.html
Describe your changes here to communicate to the maintainers why we should accept this pull request. 
=> users able to see grant project access tab

components/studio/studio/urls.py, components/studio/studio/views.py, components/studio/templates/base.html, components/studio/templates/baseproject.html, components/studio/templates/privacy.html
https://scilifelab.atlassian.net/browse/SS-177
=> SS-177 added privacy page

components/studio/studio/urls.py, components/studio/studio/views.py, components/studio/templates/base.html, components/studio/templates/contact.html
https://scilifelab.atlassian.net/browse/SS-127
=> SS-127 contact form

components/studio/templates/teaching.html
https://scilifelab.atlassian.net/browse/SS-191
=> SS-191 Moved captcha up

components/studio/templates/base.html, components/studio/templates/user_guide.html
https://scilifelab.atlassian.net/browse/SS-180
=> SS-180 request account form

components/studio/templates/base.html
https://scilifelab.atlassian.net/browse/SS-194
=> SS-194 make signup link internal

Dockerfile, requirements.txt
Decreased docker build time by moving the pip install of Pillow from requirements to dockerfile.
=> Speed-up-build

requirements.txt, studio/settings.py, studio/urls.py, templates/base.html, templates/common/navbar.html, templates/wiki/base.html, templates/wiki/wiki_footer.html, templates/wiki/wiki_top_navbar.html
This PR contains installation and integration of django-wiki into Serve.
This first version is configured for endpoint /wiki/. This can easily be modified.
This contains an initial styling of the header and footer so we can mostly test the functionality. Additional styling will be required before release. Especially the css internal to the template should be looked over and replaced if possible.
Note: No migration files are included in this PR so this will need to be added before release.
The Jira [task](https://scilifelab.atlassian.net/browse/SS-487) contains additional information about customisation and styling of the plugin as well as instructions for creating articles and content.
=> SS-487 django-wiki-guides

.github/workflows/build-and-test-studio.yaml, docker-compose.yaml, portal/tests.py, pytest.ini, requirements.txt, studio/settings.py
[JIRA LINK](https://scilifelab.atlassian.net/browse/SS-495?atlOrigin=eyJpIjoiM2IwYzJiYTI0YmNmNGYzMWJkYTNhOTcxN2E2ZGUyMDkiLCJwIjoiaiJ9)
I've integrated `pytest-django` into stackn.
It seems that there are tests in `apps`, `models`, `projects`, and `studio`. Theses tests are `django.test` and based on `unittest`. 
Two other folder contained empty test files, `monitor` and `portal`. I have added two simple tests to `portal`. 
The neat thing is that running `sh -c pytest` runs all tests. 
In `docker-compose.yaml`, i have added a `service` called `tests` and set it to not run when running `up`. The tests are then executed by running `docker-compose run tests` which i think is a neat way of doing it. Agree?
I've also added a workflow step that runs the tests.
To summarize:
- Added …
=> SS-495 implement test with pytest django

apps/controller.py, apps/helpers/helpers.py, apps/tasks.py, apps/views.py, models/views.py, monitor/helpers.py, projects/views.py, pyproject.toml
Moved explicit infile mypy ignores of library imports to configurations in the toml file. Also changed some relative imports to package imports to solve mypy rule E0402.
=> Changes for mypy such as ignoring libraries

.dockerignore, .github/workflows/build-and-test-studio.yaml, .gitignore
I have added empty folders with `.gitkeep` files as per Nikitas suggestion. I've also added these to the `.dockerignore` file. 
=> Ss 558 create empty folders and gitkeep simplify local dev setup

.github/pull_request_template.md
Updated the PR template with a reminder about also updating the settings info in serve-charts when applicable.
=> Reminder-about-serve-charts-settings-in-pr-template

.github/workflows/build-and-test-studio.yaml
Renamed studio to serve in a github action.
=> Renamed studio to serve in workflow

cypress/e2e/ui-tests/test-deploy-app.cy.js, models/views.py, portal/models.py, portal/views.py, templates/apps/new.html, templates/models/index.html, templates/portal/apps.html
Reworked the public models view.
Jira [link](https://scilifelab.atlassian.net/browse/SS-146)
=> SS-146 Public models page

charts/apps/minio/chart/templates/project-s3-deployment.yaml, charts/apps/pytorch-serve/chart/templates/deployment.yaml, charts/apps/pytorch-serve/chart/values.yaml, charts/apps/pytorch-serve/config.json, fixtures/apps_fixtures.json, fixtures/projects_templates.json, models/views.py, templates/models/model_create.html
I've changed a bunch of stuff here.
1. I've added a alpine sidecar to minio. When you create a model, this sidecar is called and it copies the specified folder from the PVC to studio
2. I've fixed the way torchserve is started and how it finds the models. This should work now
3. I've changed the model create views and forms. You do not need to specify PVC or APP anymore. It finds the model object through minio which is mounted to the PVC. This will not work if the user has multiple minio instances with multiple pvcs. It selects the first minio instance.
- …
=> SS 604 serve uses the incorrect pytorch and tensorflow images

Dockerfile, requirements.txt
Updating some versions to improve security. Goes from approx 30 critical to 0.
=> up versions to improve security

.github/pull_request_template.md, .github/workflows/ci.yaml, .github/workflows/test-and-publish.yaml, pyproject.toml
Split up the build-and-test action into two actions. A faster CI action that build and runs unit tests. And a longer-running action that runs integration and end2end tests, sets version information, and publishes the packages.
Jira [link](https://scilifelab.atlassian.net/browse/SS-629)
=> SS-629 CI and PR template

cypress/e2e/ui-tests/test-deploy-app.cy.js
=> hotfixed ui-tests

cypress/e2e/ui-tests/test-deploy-app.cy.js, cypress/e2e/ui-tests/test-project-as-contributor.cy.js
I've updated the e2e tests to find buttons that we have moved.
=> Change tests to match updated buttons

charts/apps/jupyter-lab/chart/values.yaml, charts/apps/mlflow-serve/chart/values.yaml, charts/apps/mlflow/chart/values.yaml, charts/apps/pytorch-serve/chart/values.yaml, charts/apps/rstudio/chart/values.yaml, charts/apps/shinyproxy/chart/templates/deployment.yaml, charts/apps/tensorflow-serve/chart/values.yaml, fixtures/projects_templates.json
I republished all images and updated the tags in all charts. 
I have not checked every app, and some have trivy alerts that can take days to fix. This should be a separate task.
=> SS 599 make sure we use our own images from serve images repo

apps/views.py, charts/apps/dash/config.json, charts/apps/shiny/config.json, charts/apps/shinyproxy/chart/templates/configmap.yaml, charts/apps/shinyproxy/chart/templates/deployment.yaml, charts/apps/shinyproxy/chart/templates/service.yaml, charts/apps/shinyproxy/chart/values.yaml, charts/apps/shinyproxy/config.json, fixtures/apps_fixtures.json, news/models.py, news/urls.py, news/views.py, portal/tests.py, portal/views.py, scripts/admin_token.py
This PR adds the ability to write a custom port when creating apps of type Custom, Dash, Shiny and Shinyproxy.
Jira [link](https://scilifelab.atlassian.net/browse/SS-642)
=> SS 642 custom app port

fixtures/apps_fixtures.json, templates/apps/create.html, templates/apps/update.html, templates/projects/overview.html, templates/registration/login.html
This PR makes minor adjustments to the project dashboard, as per [SS-705](https://scilifelab.atlassian.net/browse/SS-705).
=> SS-705 minor adjustments in project dashboard

common/models.py, fixtures/projects_templates.json, templates/registration/password_reset_email.html, templates/registration/verify_email.html
Fix for domain name in emails. Now we get the name from the settings file variable DOMAIN. Also fixed a small issue with netpolicy in the project template so its visible again in the projects.
=> Hotfix email domain name

templates/registration/login.html
So I decided to just update general error message for login error.
This will now look like this:
Why? It's said to be a potential security risk https://forum.djangoproject.com/t/error-message-for-inactive-users-that-try-to-login/20374
We essentially through this can leak our user's information, specifically users, that created account on our service. While not atrocious vulnerability, it's still is one. And I propose us to not take chances here and just do it this way.
- [ ] I have included migration files (if there are …
=> SS-765 added info on potential unverified email

.github/workflows/e2e-tests.yaml, common/forms.py, common/tests.py, static/js/form-helpers.js
This PR addresses issue [SS-789](https://scilifelab.atlassian.net/browse/SS-789) - now users with student emails from Swedish universities also need to be manually approved before they can start using Serve.
=> Additional new user categories need to go through manual verification

apps/helpers.py, apps/serialize.py, apps/views.py, charts/apps/custom-app/chart/templates/ingress.yaml, charts/apps/custom-app/config.json, charts/apps/dash/chart/templates/ingress.yaml, charts/apps/dash/config.json, charts/apps/jupyter-lab/config.json, charts/apps/minio/config.json, charts/apps/mlflow-serve/config.json, charts/apps/mlflow/config.json, charts/apps/python-serve/chart/templates/ingress.yaml, charts/apps/python-serve/config.json, charts/apps/pytorch-serve/chart/templates/ingress.yaml, charts/apps/pytorch-serve/config.json, charts/apps/rstudio/config.json, charts/apps/shiny/chart/templates/ingress.yaml, charts/apps/shiny/config.json, charts/apps/shinyproxy/chart/templates/ingress.yaml, charts/apps/shinyproxy/config.json, charts/apps/tensorflow-serve/chart/templates/ingress.yaml, charts/apps/tensorflow-serve/config.json, charts/apps/volumeK8s/config.json, charts/apps/vscode/config.json, fixtures/apps_fixtures.json, portal/views.py
This PR adds functionality on the backend side to make link only apps work. There will be other PR that will change frontend side as described in SS-690.
**How this was done:**
I added new privacy type to all charts and fixtures related. Then in ingress charts I added another check for "link" privacy type along side with `public` type apps. By doing this and not touching public apps page I technically achieved "link only" functionality.
But while going through code I noticed some places that should really be changed, but not in this pr. These places I marked with `TODO: refactor` for changes that should be done attentively and `TODO: minor refactor` for changes that are easy and small.
⚠️ I couldn't get to deploy an app this way, but these kind of app are definitely being deployed and not …
=> Added new privacy type on backend side

apps/views.py
=> Fixed release name ----generated---- bug

templates/apps/create.html
Added warning text about minio for release.
=> added warning about minio

scripts/admin_token.py
[SS-955](https://scilifelab.atlassian.net/browse/SS-955?atlOrigin=eyJpIjoiMDc4YWY2YmI3OWNlNGU3ZGIwZmNmM2ZlNDUxZWMxNTEiLCJwIjoiaiJ9)
I've updated the startup script to always update the password so it corresponds to whatever is set in the env variables. 
=> SS-955 updated startup script to update passwords

cypress/e2e/ui-tests/test-project-as-contributor.cy.js, templates/registration/login.html
Removed the message regarding the password reset from 2023-12-12.
=> removed login message

charts/apps/tissuumaps/chart/templates/tissuumaps-configmap.yaml
Renamed the expected TissUUmaps user data folder from shared to tissuumaps-shared.
=> Renamed TissUUmaps user data folder

apps/views.py
Fixed a "small" bug with existing path being undefined, causing volume mounts in e2e to fail.
=> fixed error

templates/portal/home.html, templates/portal/teaching.html
This PR resolves issue [SS-1016](https://scilifelab.atlassian.net/browse/SS-1016). Specifically, text about using notebooks at Serve for teaching was updated and moved to a separate user documentation page + minor improvements.
=> Updated info about using Serve for teaching

templates/portal/home.html, templates/portal/teaching.html
This PR resolves issue [SS-1016](https://scilifelab.atlassian.net/browse/SS-1016). Specifically, text about using notebooks at Serve for teaching was updated and moved to a separate user documentation page + minor improvements.
=> Update info about teaching

cypress/e2e/ui-tests/test-deploy-app.cy.js
This PR extends end2end cypress testing of the app status logic from the UI perspective.
It verifies that an edited app (Dash), when a "non redeployment" causing field is modified (app name), then the status of the app remains Running.
It also clarifies that an app with modified subdomain should eventually obtain status Running and never obtain status Deleted.
[Related Test Cases](https://scilifelab.atlassian.net/l/cp/YVSbMHy9)
=> App status end2end test improvements

api/views.py, apps/helpers.py, apps/models/base/base.py, cypress/e2e/ui-tests/test-deploy-app.cy.js, cypress/e2e/ui-tests/test-project-as-contributor.cy.js, cypress/e2e/ui-tests/test-superuser-functionality.cy.js, studio/urls.py
This PR improves debug logging of the app status logic and handling in Serve.
=> App status enhancements

apps/forms/shiny.py
To set the status of the pull request, use the built-in github feature to set the PR as Draft or Ready for review.
Describe your changes here to communicate to the maintainers why we should accept this pull request.
=> Change display of prepend text for `shiny_site_dir`

apps/helpers.py, fixtures/apps_fixtures.json
This relates to the bug in [SS-1130](https://scilifelab.atlassian.net/browse/SS-1130).
=> SS-1130 Add access to redeployment fields

cypress/e2e/ui-tests/test-superuser-functionality.cy.js
e2e test for the following task:
Source: https://scilifelab.atlassian.net/browse/SS-1236
We are updating the following four jupyterlab environments:
See https://quay.io/organization/jupyter/
We want to have:
jupyter/pytorch-notebook
jupyter/datascience-notebook
jupyter/tensorflow-notebook
jupyter/minimal-notebook
=> SS-1236 fixing e2e test for new jupyterlab environments

apps/views.py, projects/views.py
It appears that the problem was in that kubectl was trying to access the default namespace and not the `serve-dev` one.
=> SS-1288 Fix secrets view for mlflow

apps/views.py
A small pr that fixes app status query by following the new interface.
Fixes this issue https://scilifelab.atlassian.net/wiki/spaces/AIportal/pages/3487006738/Release+3.0.0-beta#expand-title-114
=> FIX app_status query for mlflow view

apps/tasks.py, fixtures/apps_fixtures.json
Pin mlflow version
Split charts by regex in helm install celery task
To set the status of the pull request, use the built-in github feature to set the PR as Draft or Ready for review.
Describe your changes here to communicate to the maintainers why we should accept this pull request.
=> SS-1288 Pin mlflow version

fixtures/apps_fixtures.json, fixtures/projects_templates.json
[https://scilifelab.atlassian.net/browse/SS-853](https://scilifelab.atlassian.net/browse/SS-853)
Bump the version of Rstudio and helm chart versions following an image upgrade.
=> SS-853 Upgrade Rstudio image and chart versions

fixtures/apps_fixtures.json
Updating file manager
Jira link: https://scilifelab.atlassian.net/browse/SS-1234
=> SS-1234 Updating file manager

apps/tasks.py, templates/projects/categories/develop.html
To set the status of the pull request, use the built-in github feature to set the PR as Draft or Ready for review.
Describe your changes here to communicate to the maintainers why we should accept this pull request.
=> Exclude mlflow apps from periodic deletion task

fixtures/apps_fixtures.json
Updates the docker image for VScode with pip and Jupyter module pre-set as default.
Jira [link](https://scilifelab.atlassian.net/browse/SS-1235)
=> SS-1235 Update VScode image

api/views.py, apps/admin.py, apps/constants.py, apps/helpers.py, apps/tasks.py, apps/tests/test_app_helper_utils.py, apps/tests/test_update_status_handler.py, apps/views.py, projects/tasks.py, templates/projects/categories/develop.html
Merge Hotfix from main into staging.
=> Merge Hotfix SS 1348 from main into staging

apps/models/app_types/mlflow.py
This fixes mlflow giving out of memory error.
Without this mlflow's pod restarts on page load with OOM error
=> SS-1383 This fixes mlflow giving out of memory error

apps/models/app_types/custom/streamlit.py
Decreased upload size for streamlit apps to 100mb according to streamlit documentation https://docs.streamlit.io/knowledge-base/deploy/increase-file-uploader-limit-streamlit-cloud
=> SS-1333 Decreased upload size for streamlit apps to 100mb

cypress/e2e/ui-tests/test-project-as-contributor.cy.js, cypress/e2e/ui-tests/test-public-webpages.cy.js, cypress/e2e/ui-tests/test-superuser-functionality.cy.js, portal/views.py, static/css/serve-elements.css, templates/common/analytics.html, templates/common/app_card.html, templates/portal/apps.html
Fixing e2e tests after merging SS-613.
=> Fix e2e tests

portal/views.py, static/css/serve-elements.css, templates/portal/apps.html
=> Release 3.2.0 bug fixes

apps/helpers.py, templates/common/app_metadata.html
Ready for review.
fixing app-landing-page no-image bug
=> fixing app-landing-page no-image bug

fixtures/apps_fixtures.json
Ready for review
Source: https://scilifelab.atlassian.net/browse/SS-1473
Bump the versions of the charts for every app to the latest current versions.
=> SS-1473 bumping up app chart versions

api/openapi/content_stats_api.py, api/tests/test_openapi_content_stats.py, apps/models/app_types/mlflow.py, portal/views.py, static/css/serve-elements.css, templates/common/app_card.html, templates/portal/apps.html
Reverts ScilifelabDataCentre/serve#352
=> Revert "Fix SS-1481, Unable to create new MLFlow app instance (#351)"

apps/views.py, projects/views.py, studio/urls.py, templates/apps/create_base.html, templates/projects/partials/project_description.html, templates/projects/partials/project_header.html
Add admin view links for authenticated staff users in project and app templates
=> Add admin view links for authenticated staff users in project and app templates

templates/common/app_metadata.html
Ready for review.
Remove technical details that we don’t want on it.
Source: https://scilifelab.atlassian.net/browse/SS-1493
=> SS-1493 Improve app details page

docker-compose.yaml
This PR upgrades the version of the event listener used in the developer's docker compose setup.
There will likely be a version 1.2.1 or 1.3 before the next release, so this is mainly just for developers' convenience.
=> Upgrade event listener used to v1.2.0 in docker compose

.env.template, api/views.py, docker-compose.yaml
This PR bumps the version of the event listener to v1.3.0 for docker compose development and adds some new associated environment variables to the .env.template file.
It also includes some more app attributes in the API endpoint content-review
=> SS 1254 Use event listener v1.3.0 for development
